// Generated by https://quicktype.io

export interface MovieDetail {
    id:               number;
    title:            string;
    overview:         string;
    tagline:          string;
    budget:           number;
    revenue:          null;
    imdbUrl:          string;
    tmdbUrl:          string;
    posterUrl:        string;
    backdropUrl:      string;
    originalLanguage: string;
    releaseDate:      string;
    runTime:          number;
    rating:           number;
    price:            number;
    purchaseStat:     null;
    trailers:         Trailer[];
    genres:           Genre[];
    casts:            Cast[];
}

export interface Cast {
    id:        number;
    name:      string;
    character: string;
    posterUrl: string;
}

export interface Genre {
    id:   number;
    name: string;
}

export interface Trailer {
    id:         number;
    movieId:    number;
    trailerUrl: string;
    name:       string;
}
