// Generated by https://quicktype.io

export interface Purchase {
    id:               number;
    userId:           number;
    purchaseNumber:   string;
    totalPrice:       number;
    purchaseDateTime: string;
    movieCard:        MovieCard;
}

export interface MovieCard {
    id:        number;
    title:     string;
    posterUrl: string;
}
